services:
  - type: web
    name: badminton-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    startCommand: bash run.sh  # Explicitly set start command
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: badminton-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: badminton-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
